import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import {JSDOM} from 'jsdom';

const root=path.resolve(process.argv[2]||path.join(path.dirname(fileURLToPath(import.meta.url)),'..'));
const html=await readFile(path.join(root,'index.html'),'utf8');
const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});
const {window}=dom,errors=[],draw={count:0,methods:new Set(),text:[]},audio={count:0,contexts:0,methods:new Set()};window.__ppDrawCalls=0;window.__ppDrawText=[];
let harnessRandom=0x58c0de;window.Math.random=()=>{harnessRandom=(harnessRandom*1664525+1013904223)>>>0;return harnessRandom/4294967296;};
const originalError=window.console.error.bind(window.console);window.console.error=(...args)=>{const first=args[0];if(String(first).includes('[RENDER]'))errors.push({kind:'render',message:args.map(String).join(' '),stack:args.find(x=>x?.stack)?.stack||''});originalError(...args);};
window.onerror=(message,source,line,col,error)=>{errors.push({kind:'window.onerror',message,source,line,col,stack:error?.stack||''});};
window.addEventListener('unhandledrejection',e=>errors.push({kind:'unhandledrejection',message:String(e.reason),stack:e.reason?.stack||''}));
const methodNames=['setTransform','fillRect','strokeRect','clearRect','beginPath','closePath','moveTo','lineTo','quadraticCurveTo','bezierCurveTo','arc','arcTo','ellipse','rect','fill','stroke','clip','save','restore','translate','rotate','scale','setLineDash','fillText','strokeText','measureText','createRadialGradient','createLinearGradient','createPattern','drawImage'];
const canvasContext={};for(const name of methodNames)canvasContext[name]=(...args)=>{draw.count++;window.__ppDrawCalls++;draw.methods.add(name);if(name==='fillText'||name==='strokeText'){draw.text.push(String(args[0]));window.__ppDrawText.push(String(args[0]));}return name.includes('Gradient')?{addColorStop(){}}:name==='measureText'?{width:0}:undefined;};
Object.defineProperty(window.HTMLCanvasElement.prototype,'getContext',{value(){return canvasContext;}});
Object.defineProperty(window.HTMLCanvasElement.prototype,'clientWidth',{get(){return 1280;}});
Object.defineProperty(window.HTMLCanvasElement.prototype,'clientHeight',{get(){return 800;}});
window.HTMLCanvasElement.prototype.getBoundingClientRect=function(){return {x:0,y:0,left:0,top:0,width:1280,height:800,right:1280,bottom:800,toJSON(){return this;}};};
window.matchMedia=()=>({matches:false,media:'',addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});
window.visualViewport={width:1280,height:800,addEventListener(){},removeEventListener(){}};
window.navigator.vibrate=()=>true;
Object.defineProperty(window.document,'hidden',{value:false,writable:true,configurable:true});
const audioCall=(name)=>{audio.count++;audio.methods.add(name);};
const param=()=>({value:0,setValueAtTime(){audioCall('AudioParam.setValueAtTime');},linearRampToValueAtTime(){audioCall('AudioParam.linearRampToValueAtTime');},exponentialRampToValueAtTime(){audioCall('AudioParam.exponentialRampToValueAtTime');},setTargetAtTime(){audioCall('AudioParam.setTargetAtTime');},cancelScheduledValues(){audioCall('AudioParam.cancelScheduledValues');}});
const node=(kind)=>({kind,connect(){audioCall(`${kind}.connect`);return this;},disconnect(){audioCall(`${kind}.disconnect`);},start(){audioCall(`${kind}.start`);},stop(){audioCall(`${kind}.stop`);},gain:param(),frequency:param(),detune:param(),Q:param(),pan:param(),playbackRate:param(),threshold:param(),knee:param(),ratio:param(),attack:param(),release:param(),type:'sine',setPeriodicWave(){audioCall(`${kind}.setPeriodicWave`);}});
class StubAudioContext{
  constructor(){audio.contexts++;audioCall('AudioContext.constructor');this.state='running';this.currentTime=0;this.sampleRate=48000;this.destination=node('Destination');}
  createGain(){audioCall('AudioContext.createGain');return node('GainNode');}
  createOscillator(){audioCall('AudioContext.createOscillator');return node('OscillatorNode');}
  createBiquadFilter(){audioCall('AudioContext.createBiquadFilter');return node('BiquadFilterNode');}
  createDynamicsCompressor(){audioCall('AudioContext.createDynamicsCompressor');return node('DynamicsCompressorNode');}
  createBufferSource(){audioCall('AudioContext.createBufferSource');return Object.assign(node('BufferSource'),{buffer:null,loop:false});}
  createStereoPanner(){audioCall('AudioContext.createStereoPanner');return node('StereoPannerNode');}
  createBuffer(channels,length,rate){audioCall('AudioContext.createBuffer');return {numberOfChannels:channels,length,sampleRate:rate,getChannelData(){return new Float32Array(length);}};}
  createPeriodicWave(){audioCall('AudioContext.createPeriodicWave');return {};}
  decodeAudioData(){audioCall('AudioContext.decodeAudioData');return Promise.resolve(this.createBuffer(1,1,this.sampleRate));}
  resume(){audioCall('AudioContext.resume');this.state='running';return Promise.resolve();}
  suspend(){audioCall('AudioContext.suspend');this.state='suspended';return Promise.resolve();}
  close(){audioCall('AudioContext.close');return Promise.resolve();}
}
window.AudioContext=StubAudioContext;window.webkitAudioContext=StubAudioContext;
window.ResizeObserver=class{constructor(fn){this.fn=fn;}observe(){audioCall('ResizeObserver.observe');}unobserve(){}disconnect(){}};
window.IntersectionObserver=class{constructor(fn){this.fn=fn;}observe(){audioCall('IntersectionObserver.observe');}unobserve(){}disconnect(){}};
window.requestIdleCallback=(fn)=>setTimeout(()=>fn({didTimeout:false,timeRemaining:()=>10}),0);
window.cancelIdleCallback=(id)=>clearTimeout(id);
window.navigator.wakeLock={request:async()=>({release:async()=>{},addEventListener(){}})};
let rafId=0;const rafQueue=[];window.requestAnimationFrame=fn=>{if(rafQueue.length<8)rafQueue.push(fn);return ++rafId;};window.cancelAnimationFrame=()=>{};
const scripts=[...dom.window.document.querySelectorAll('script[src]')].map(s=>s.getAttribute('src'));
const context=dom.getInternalVMContext();
for(const src of scripts){const file=src.replace(/^\.\//,'');try{vm.runInContext(await readFile(path.join(root,file),'utf8')+`\n//# sourceURL=${file}`,context,{filename:file});}catch(error){errors.push({kind:'script',file,message:error.message,stack:error.stack});break;}}
if(errors.length){console.log(JSON.stringify(errors,null,2));process.exit(1);}
const gestureStates=[];
window.document.dispatchEvent(new window.MouseEvent('mousedown',{bubbles:true,button:0}));
await Promise.resolve();
gestureStates.push({event:'mousedown',state:vm.runInContext("typeof audio!=='undefined' ? (audio.ctx?.state||'none') : 'missing'",context)});
window.document.dispatchEvent(new window.Event('touchstart',{bubbles:true}));
await Promise.resolve();
gestureStates.push({event:'touchstart',state:vm.runInContext("typeof audio!=='undefined' ? (audio.ctx?.state||'none') : 'missing'",context)});
const visibilityStates=await (async()=>{window.document.hidden=true;window.document.dispatchEvent(new window.Event('visibilitychange'));await Promise.resolve();const hidden=vm.runInContext("typeof audio!=='undefined' ? (audio.ctx?.state||'none') : 'missing'",context);window.document.hidden=false;window.document.dispatchEvent(new window.Event('visibilitychange'));await Promise.resolve();await Promise.resolve();return{hidden,visible:vm.runInContext("typeof audio!=='undefined' ? (audio.ctx?.state||'none') : 'missing'",context),event:vm.runInContext("typeof audio!=='undefined' ? (audio.audioStats?.().lastGestureEvent||null) : null",context)};})();
const patrolSmoke=vm.runInContext("(()=>{game.dispatch({type:'NEW_PATROL',areaKey:'Truk Approaches',missionType:'HARBOR_STRIKE',gameIdentity:{campaignId:'pacific-submarine-war',warPartyId:'pacific-usa',theaterId:'pacific',playerFactionId:'usa',campaignProfileId:'us-pacific',submarineProfileId:'gato-silversides'}});game.engine.processCommands();game.update(0.5);return {harbor:!!game.state.world.harbor,initialized:!!game.state.world.harborInitialized,area:game.state.campaign.patrolArea,profile:game.state.campaign.campaignProfileId,op:!!getCampaignHarborOperationProfile(game.state.campaign.campaignProfileId)};})()",context);
const standardPatrolSmoke=vm.runInContext("(()=>{game.dispatch({type:'NEW_PATROL',areaKey:'Solomon Sea',gameIdentity:{campaignId:'pacific-submarine-war',warPartyId:'pacific-usa',theaterId:'pacific',playerFactionId:'usa',campaignProfileId:'us-pacific',submarineProfileId:'gato-silversides'}});game.engine.processCommands();game.update(0.5);const s=game.state,sub=s.playerSub;return{area:s.campaign.patrolArea,position:{...sub.position},depth:sub.depthFeet,seabed:sub.seabedFeet,clearance:sub.keelClearanceFeet,hull:sub.damage.hullIntegrity,mode:sub.mode,forcedSea:s.world._devForcedSeabedFeet??null};})()",context);
const spawnDepthChecks=vm.runInContext("(()=>['Solomon Sea','Truk Approaches','Sulu Sea / Tawi-Tawi'].map(area=>{game.dispatch({type:'NEW_PATROL',areaKey:area,gameIdentity:{campaignId:'pacific-submarine-war',warPartyId:'pacific-usa',theaterId:'pacific',playerFactionId:'usa',campaignProfileId:'us-pacific',submarineProfileId:'gato-silversides'}});game.engine.processCommands();game.update(.1);const s=game.state,u=s.playerSub;return{area,position:{...u.position},seabed:u.seabedFeet,clearance:u.keelClearanceFeet,hull:u.damage.hullIntegrity,ok:u.keelClearanceFeet>=30&&u.damage.hullIntegrity>=100};}))()",context);
vm.runInContext("game.dispatch({type:'NEW_PATROL',areaKey:'Truk Approaches',missionType:'HARBOR_STRIKE',gameIdentity:{campaignId:'pacific-submarine-war',warPartyId:'pacific-usa',theaterId:'pacific',playerFactionId:'usa',campaignProfileId:'us-pacific',submarineProfileId:'gato-silversides'}});game.engine.processCommands();game.update(.1)",context);
const torpedoSmoke=vm.runInContext("(()=>{const t0=game.state.world.contacts.find(c=>c.harborTarget);if(!t0)return {launched:false,hit:false,reason:'no target'};game.state.world.harbor.netRangeNm=0;game.state.playerSub.depthFeet=60;const ready=game.state.weapons.tubes[0];ready.status='LOADED_DRY';game.dispatch({type:'FLOOD_TUBE',tubeId:ready.id});game.engine.processCommands();const flooded=ready.status==='READY';game.state.tdc.targetId=t0.id;game.state.tdc.autoTrack=false;game.state.tdc.bearing=90;game.state.tdc.rangeNm=.7;game.state.tdc.targetCourse=0;game.state.tdc.targetSpeedKnots=0;game.state.tdc.torpedoSpecKey='mk14fast';game.state.tdc.gyroAngle=0;game.state.tdc.solutionCourse=game.state.playerSub.heading;game.state.tdc.solutionQuality=1;game.state.tdc.launchBank=null;game.dispatch({type:'FIRE_TORPEDO',tubeId:ready.id});game.engine.processCommands();const t=game.state.weapons.activeTorpedoes[0];if(!t)return {launched:false,hit:false,flooded,reason:'fire rejected'};t.position={...t0.position};t.speedKnots=0;t.armedAfterNm=0;t.rangeRunNm=1;const hit=game.engine.sys.torpedoes.torpedoShipSweepHit(t,t.position,t0);game.update(0.05);return {flooded,launched:true,hit:!!hit||t0.damage?.hits>0||t0.health<t0.maxHealth||game.state.tactical.impactObservation?.weapon==='TORPEDO'};})()",context);
const sinkingSmoke=vm.runInContext("(()=>{const s=game.state,c=s.world.contacts.find(x=>x.side!=='FRIENDLY'&&!x.sunk&&x.position);if(!c)return{sunk:false,continues:false,reason:'no target'};const D=ensureShipDamage(c);D.flotation=1;D.founderingAt=s.time.elapsedSeconds;updateShipDamage(game.engine.ctx,c,0);const sunk=!!c.sunk;game.update(.1);return{sunk,continues:s.campaign.missionStatus!=='LOST',captainLogPath:!!s.runtime?.aar};})()",context);
const sonarSmoke=vm.runInContext("(()=>{const s=game.state,c=s.world.contacts.find(x=>!x.sunk&&x.position);if(!c)return{commanded:false,echo:false};s.tactical.activeStation='SOUND';s.tactical.soundBearing=bearingBetween(s.playerSub.position,c.position);s.world.sound=s.world.sound||{};s.world.sound.activeEchoLastAt=-999;game.dispatch({type:'SOUND_ECHO_RANGE'});game.engine.processCommands();return{commanded:true,echo:s.world.sound.qcLastAt===s.time.elapsedSeconds||Number.isFinite(s.world.sound.qcLastAt),heard:s.world.sound.qcVisual!=null};})()",context);
const deckGunSmoke=vm.runInContext("(()=>{const s=game.state,c=s.world.contacts.find(x=>x.harborTarget&&!x.sunk),sub=s.playerSub,G=s.weapons.deckGun;if(!c||!G)return{laid:false,fired:false,hit:false};sub.depthFeet=0;sub.mode='SURFACED';sub.heading=0;s.time.timeScale=1;s.world.environment.seaState=0;c.position={xNm:sub.position.xNm,yNm:sub.position.yNm-.3};c.heading=90;c.speedKnots=0;s.tactical.selectedTrackId=c.id;G.manned=true;G.ammo=Math.max(2,G.ammo||0);G.lastFireAt=-999;game.dispatch({type:'LAY_DECK_GUN'});game.engine.processCommands();const laid=Number.isFinite(G.trainDeg)&&Number.isFinite(G.elevationDeg);game.dispatch({type:'FIRE_DECK_GUN'});game.engine.processCommands();const shell=G.shells.at(-1),fired=!!shell,before=G.hits||0;if(shell)game.engine.sys.deckGun.damageShipByDeckGun(c,{along:0,lateral:0,z:4},shell);return{laid,fired,hit:(G.hits||0)>before};})()",context);
const aaAudioBefore=audio.count;
const aaSmoke=vm.runInContext("(()=>{const s=game.state,W=s.world,sub=s.playerSub,oldRandom=Math.random;sub.depthFeet=0;sub.mode='SURFACED';W.environment.daylight=1;W.environment.seaState=0;W.aaManned=true;W.airThreat=W.airThreat||{};W.airThreat.nextCheck=999;W.airThreat.friendlyNextCheck=999;const a={id:'AA-SMOKE',side:'ENEMY',name:'Test attacker',kind:'BOMBER',ordnance:'BOMB',position:{...sub.position},heading:0,speedKnots:0,state:'STRAFING',bombs:1,runTimer:0,spotted:true,seenBySub:true,bornAt:s.time.elapsedSeconds,passes:0,rattled:0};W.aircraft=[a];const before=W.aaHurt||0;try{Math.random=()=>0;game.engine.sys.aircraft.update(game.engine.ctx,.1);game.engine.sys.aaGun.airAttack(a,sub,sub.position);processPresentationEffects();}finally{Math.random=oldRandom;}return{attackPath:a.passes>0,casualty:(W.aaHurt||0)>before,aaManned:W.aaManned};})()",context);
aaSmoke.bombCue=audio.count>aaAudioBefore;
const impactAge=vm.runInContext("(()=>{const s=game.state;s.tactical.impactObservation={token:9001,position:{xNm:0,yNm:0},impactPosition:{xNm:0,yNm:0},viewerPos:{xNm:0,yNm:0},durationMs:9000,preImpactMs:0,weapon:'TORPEDO',torpedoWakeVisible:false};s.runtime.presentation={impactToken:9001,impactStartedWall:performance.now()-1000};canvasView.render(s,LayoutService.get());return canvasView.lastImpactAge||0;})()",context);
const cinematicInit=vm.runInContext("(()=>{const mk=t=>({token:t,position:{xNm:0,yNm:0},impactPosition:{xNm:0,yNm:0},viewerPos:{xNm:0,yNm:0},durationMs:500,preImpactMs:0,weapon:'TORPEDO',torpedoWakeVisible:false});const s=game.state;s.time.modalPauses=0;s.time.timeScale=1;s.tactical.impactObservation=null;s.runtime.presentation={};[9101,9102,9103].forEach(t=>{game.engine.startImpactObservation(mk(t));processPresentationEffects();});game.engine.processCommands();const fourth=game.engine.startImpactObservation(mk(9104));processPresentationEffects();const saved=SaveSystem._cloneStateForStorage(s),loaded=SaveSystem._normalizeLoadedState(saved);return{fourth,queued:s.runtime.presentation.impactQueue.map(x=>x.token),save:{timeScale:loaded.time.timeScale,modalPauses:loaded.time.modalPauses,impact:!!loaded.tactical.impactObservation,presentation:loaded.runtime?.presentation||null}};})()",context);
const cinematicFrames=[];for(const token of [9101,9102,9103]){const frame=vm.runInContext("(()=>{const p=game.state.runtime.presentation;p.impactStartedWall=performance.now()-1000;globalThis.__ppDrawText=[];const before=globalThis.__ppDrawCalls;canvasView.render(game.state,LayoutService.get());return{token:game.state.tactical.impactObservation?.token,age:canvasView.lastImpactAge,draws:globalThis.__ppDrawCalls-before,label:globalThis.__ppDrawText.find(x=>/^HIT 1 OF/.test(x))||null,pauses:game.state.time.modalPauses};})()",context);cinematicFrames.push(frame);if(token!==9103)await new Promise(resolve=>setTimeout(resolve,550));}
await new Promise(resolve=>setTimeout(resolve,550));vm.runInContext("game.engine.processCommands()",context);const cinematicChecks={...cinematicInit,frames:cinematicFrames,final:vm.runInContext("({active:game.state.tactical.impactObservation?.token||null,pauses:game.state.time.modalPauses,timeScale:game.state.time.timeScale,queue:game.state.runtime.presentation.impactQueue.length})",context)};
const queueViewSmoke=vm.runInContext("(()=>{const s=game.state,p=s.runtime.presentation,mk=t=>({token:t,position:{xNm:0,yNm:0},durationMs:900,preImpactMs:0,weapon:'TORPEDO'});s.tactical.impactObservation=mk(9201);p.impactToken=9201;p.impactStartedWall=performance.now()-1200;p.impactQueue=[mk(9202)];const b=document.createElement('button');document.body.appendChild(b);b.dispatchEvent(new MouseEvent('pointerdown',{bubbles:true}));const unchanged=s.tactical.impactObservation?.token===9201&&p.impactQueue.length===1;b.remove();s.tactical.impactObservation=null;p.impactToken=null;p.impactQueue=[];return{viewPointerDoesNotSkip:unchanged};})()",context);
for(let i=0;i<5&&rafQueue.length;i++){const fn=rafQueue.shift();try{fn(i*16.67);}catch(error){errors.push({kind:'raf',message:error.message,stack:error.stack});}}
const stationResults=[];
for(const station of [...new Set([...window.document.querySelectorAll('[data-sta]')].map(b=>b.dataset.sta).filter(Boolean))]){const button=[...window.document.querySelectorAll('[data-sta]')].find(b=>b.dataset.sta===station),beforeErrors=errors.length;try{button.dispatchEvent(new window.Event('click',{bubbles:true}));}catch(error){errors.push({kind:'station-dispatch',station,message:error.message,stack:error.stack});}stationResults.push({station,rendered:errors.length===beforeErrors,ok:errors.length===beforeErrors});}
const applyCmdInventory=['PAUSE_FOR_MODAL','RESUME_FROM_MODAL','END_IMPACT_OBSERVATION','PLAY_AUDIO','APPEND_LOG','SET_ORDERED_HEADING','SET_ENGINE_RPM','SET_ORDERED_DEPTH','SURFACE','DIVE','PERISCOPE_DEPTH','CRASH_DIVE','TOGGLE_AIR_WARNING_RADAR','TOGGLE_SD_RADAR','BOTTOM_OUT','TOGGLE_AA_GUN','TOGGLE_DECK_GUN','ADJUST_DECK_GUN','SET_DECK_GUN_ELEVATION','LAY_DECK_GUN','FIRE_DECK_GUN','TOGGLE_SILENT_RUNNING','RADIO_TOGGLE_SILENCE','RADIO_AUTHORIZE_REPORT','RADIO_ACCEPT_PARTIAL','EMERGENCY_BLOW','TOGGLE_DAMAGE_CONTROL','SET_REPAIR_PRIORITY','TOGGLE_PUMPS','START_TRANSIT','STOP_TRANSIT','SET_TIME_SCALE','CYCLE_TIME_SCALE','SET_ACTIVE_STATION','ROTATE_SOUND','SOUND_MARK_BEARING','SOUND_ECHO_RANGE','TOGGLE_SOUND_DISPLAY','ROTATE_BRIDGE','TOGGLE_BRIDGE_BINOCULARS','SET_BRIDGE_ZOOM','BRIDGE_MARK_CONTACT','BRIDGE_TARGET_CENTER','BRIDGE_TARGET_CONTACT','ROTATE_PERISCOPE','SET_PERISCOPE_ZOOM','TOGGLE_PERISCOPE_ZOOM','PERISCOPE_SELECT_CENTER_CONTACT','DESELECT_TRACK','SELECT_TRACK','TDC_SEND_SCOPE_OBSERVATION','FLOOD_TUBE','FIRE_TORPEDO','FLOOD_ALL_TUBES','FIRE_READY_SPREAD','SET_TORPEDO_TYPE','SET_DUD_MODE','SET_TORPEDO_DEPTH','SET_TDC_MANUAL','APPLY_TDC_MANUAL','FLOOD_AFT_TUBES','FIRE_AFT_SPREAD','MAP_ADD_WAYPOINT','MAP_REMOVE_WAYPOINT','TOGGLE_AUTOPILOT','MAP_CLEAR_PLOT','PLOT_INTERCEPT_ADVISORY','TOGGLE_MAP_WEATHER','MAP_STEER_TO_NEXT_WAYPOINT','HEAD_TO_PORT','NEW_PATROL'];
const cmdArgs={PLAY_AUDIO:{method:'playUiConfirm'},APPEND_LOG:{message:'COMMAND SMOKE'},SET_ORDERED_HEADING:{heading:90},SET_ENGINE_RPM:{rpm:120},SET_ORDERED_DEPTH:{depthFeet:0},ADJUST_DECK_GUN:{deltaTrainDeg:1},SET_DECK_GUN_ELEVATION:{elevationDeg:2},SET_REPAIR_PRIORITY:{priority:'FLOODING'},START_TRANSIT:{seconds:1},SET_TIME_SCALE:{scale:1},SET_ACTIVE_STATION:{station:'MAP'},ROTATE_SOUND:{deltaDeg:5},BRIDGE_MARK_CONTACT:{trackId:null},BRIDGE_TARGET_CONTACT:{trackId:null},SET_BRIDGE_ZOOM:{zoom:.5},ROTATE_BRIDGE:{deltaDeg:5},ROTATE_PERISCOPE:{deltaDeg:5},SET_PERISCOPE_ZOOM:{zoom:1},FLOOD_TUBE:{tubeId:1},FIRE_TORPEDO:{tubeId:1},SET_TORPEDO_TYPE:{specKey:'mk14fast'},SET_DUD_MODE:{mode:'OFF'},SET_TORPEDO_DEPTH:{depthFt:55},SET_TDC_MANUAL:{bearing:90,range:1,course:90,speed:0},MAP_ADD_WAYPOINT:{point:{xNm:0,yNm:0}},MAP_REMOVE_WAYPOINT:{index:0},SELECT_TRACK:{trackId:null},END_IMPACT_OBSERVATION:{token:-1}};
const commandSmoke=vm.runInContext(`(()=>{const names=${JSON.stringify(applyCmdInventory)},args=${JSON.stringify(cmdArgs)},failed=[];for(const type of names){try{game.dispatch({type,...(args[type]||{})});game.engine.processCommands();}catch(e){failed.push({type,message:e.message});}}return{total:names.length,executed:names.length-failed.length,failed};})()`,context);
const patrolCompletionSmoke=vm.runInContext("(()=>{game.dispatch({type:'NEW_PATROL',areaKey:'Solomon Sea',gameIdentity:{campaignId:'pacific-submarine-war',warPartyId:'pacific-usa',theaterId:'pacific',playerFactionId:'usa',campaignProfileId:'us-pacific',submarineProfileId:'gato-silversides'}});game.engine.processCommands();game.update(.1);const before=game.state.runtime.careerRecords?.length||0;game.engine.completeMission('HARNESS PORT');const records=game.state.runtime.careerRecords||[],record=records.at(-1),replay=record?.replay;return{recordAdded:records.length===before+1,recordId:record?.id||null,outcome:record?.outcome||null,captainReturnLogged:!!record?.importantEvents?.some(e=>e.type==='RETURNED_TO_PORT'),replayBuilt:!!replay,replayVersion:replay?.version||null,replayHasArrays:!!replay&&['route','observedTracks','truthTracks','events','torpedoes','gunRounds','enemyResponses'].every(k=>Array.isArray(replay[k]))};})()",context);
const gameLoopStarted=errors.every(e=>e.file!=='js/bootstrap/start.js')&&rafId>0;
const canvases=[...window.document.querySelectorAll('canvas')].map(c=>({id:c.id,width:c.width,height:c.height,clientWidth:c.clientWidth,clientHeight:c.clientHeight}));
dom.window.close();
console.log(JSON.stringify({root,firstException:errors[0]||null,errors,gameLoopStarted,drawCalls:draw.count,audioCalls:audio.count,audioContexts:audio.contexts,gestureStates,visibilityStates,patrolSmoke,standardPatrolSmoke,spawnDepthChecks,torpedoSmoke,sinkingSmoke,sonarSmoke,deckGunSmoke,aaSmoke,impactAge,cinematicChecks,queueViewSmoke,commandSmoke,patrolCompletionSmoke,audioMethods:[...audio.methods],drawMethods:[...draw.methods],canvases,stations:stationResults},null,2));
if(errors.length||!draw.count||!audio.count||audio.contexts!==1||!patrolSmoke.harbor||standardPatrolSmoke.hull<100||standardPatrolSmoke.clearance<30||spawnDepthChecks.some(x=>!x.ok)||!torpedoSmoke.flooded||!torpedoSmoke.launched||!torpedoSmoke.hit||!sinkingSmoke.sunk||!sinkingSmoke.continues||!sonarSmoke.commanded||!sonarSmoke.echo||!deckGunSmoke.laid||!deckGunSmoke.fired||!deckGunSmoke.hit||!aaSmoke.attackPath||!aaSmoke.casualty||!aaSmoke.bombCue||impactAge<=0||cinematicChecks.queued.length!==2||cinematicChecks.fourth!==false||cinematicChecks.frames.map(x=>x.token).join(',')!=='9101,9102,9103'||cinematicChecks.frames.some(x=>x.age<=0||x.draws<=0||x.pauses!==1)||cinematicChecks.frames[0].label!=='HIT 1 OF 3 · TAP TO SKIP'||cinematicChecks.frames[1].label!=='HIT 1 OF 2 · TAP TO SKIP'||cinematicChecks.final.active!==null||cinematicChecks.final.pauses!==0||cinematicChecks.final.timeScale===0||cinematicChecks.final.queue!==0||cinematicChecks.save.timeScale===0||cinematicChecks.save.modalPauses!==0||cinematicChecks.save.impact||Object.keys(cinematicChecks.save.presentation).length||!queueViewSmoke.viewPointerDoesNotSkip||commandSmoke.failed.length||!patrolCompletionSmoke.recordAdded||!patrolCompletionSmoke.captainReturnLogged||!patrolCompletionSmoke.replayBuilt||!patrolCompletionSmoke.replayHasArrays||gestureStates.some(g=>g.state!=='running')||visibilityStates.hidden!=='suspended'||visibilityStates.visible!=='running'||canvases.some(c=>c.width<=0||c.height<=0)||stationResults.some(s=>!s.rendered))process.exitCode=1;
