import {readdir,readFile,stat} from 'node:fs/promises';import path from 'node:path';import process from 'node:process';
const root=path.resolve(process.argv[2]||'.'),fail=[];async function files(dir){const out=[];for(const e of await readdir(dir,{withFileTypes:true})){if(['.git','tests'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await files(p));else out.push(p);}return out;}
const all=await files(root),sized=await Promise.all(all.map(async p=>[p,(await stat(p)).size])),sum=filter=>sized.filter(([p])=>filter(p)).reduce((n,[,b])=>n+b,0),rel=p=>path.relative(root,p);
const budgets={repository:2_650_000,javascript:1_850_000,styles:220_000,audio:650_000,singleScript:145_000},values={repository:sum(()=>true),javascript:sum(p=>p.endsWith('.js')),styles:sum(p=>p.endsWith('.css')),audio:sum(p=>/\.(mp3|ogg|wav|m4a)$/i.test(p)),singleScript:Math.max(...sized.filter(([p])=>p.endsWith('.js')).map(([,b])=>b))};
for(const [k,v] of Object.entries(values))if(v>budgets[k])fail.push(`${k} ${v} > ${budgets[k]}`);
const read=async p=>readFile(path.join(root,p),'utf8'),css=await read('css/app.css'),toast=await read('js/ui/toast.js'),wiring=await read('js/bootstrap/wiring.js'),selector=await read('js/ui/scenario-selector.js'),audio=await read('js/audio/audio-engine.js'),engine=await read('js/simulation/engine-core.js'),map=await read('js/rendering/map.js'),mission=await read('js/simulation/mission-framework.js'),asw=await read('js/simulation/ai/asw-brain.js'),escort=await read('js/simulation/ai/escort-asw.js'),enemy=await read('js/simulation/ai/enemy-ai.js'),ships=await read('js/rendering/world-geometry.js');
if(!css.includes('#deskScopeControls{display:none;}'))fail.push('touch scope controls are not hidden by default');if(!css.includes('grid-template-columns:64px minmax(0,1fr)'))fail.push('narrow intel layout gate missing');if(!toast.includes('const DecisionDialog='))fail.push('game-native decision dialog missing');if(/(^|[^\w.])confirm\s*\(/m.test(selector+wiring))fail.push('native confirm remains in selector/wiring');if(!audio.includes('hybridBudgetBytes=8*1024*1024'))fail.push('hybrid audio memory budget missing');if(!wiring.includes('qualityBudget(samples=6)'))fail.push('runtime performance budget missing');if(!engine.includes('planNavigableCourse(from,to)')||!engine.includes('WAYPOINT REFUSED'))fail.push('water-safe waypoint planning missing');if(!map.includes("const activeThreat=")||!map.includes("alertState==='ATTACKING'"))fail.push('escort threat colour rule missing');
if(!engine.includes('navigationCorridors')||!engine.includes('corridor ${i} leaves navigable water'))fail.push('charted corridor water validation missing');if(!map.includes('drawNavigationCorridors(ctx,corridors,w2s)'))fail.push('charted corridor renderer missing');if(!mission.includes('_missionUpdatePacing(engine,m,dt)')||!mission.includes('targetMinutes:30'))fail.push('30-minute pacing director missing');
for(const key of ['US_FLETCHER_DESTROYER','US_DESTROYER_ESCORT','GERMAN_TORPEDO_BOAT','GERMAN_MINESWEEPER','ITALIAN_SOLDATI_DESTROYER','ITALIAN_GABBIANO_CORVETTE','SOVIET_GNEVNY_DESTROYER','SOVIET_PATROL_ESCORT'])if(!ships.includes(`SHIP_MODELS.${key}=`))fail.push(`national silhouette missing: ${key}`);
if(!asw.includes('function aswTactics(state)')||!asw.includes("pattern==='SECTOR'")||!asw.includes("pattern==='CIRCULAR'"))fail.push('country/year ASW tactics missing');if(!escort.includes('tactics.speculativeAttackFactor*training')||!escort.includes('tactics.depthErrorFactor/training'))fail.push('ASW training is not applied to attack decisions');if(!escort.includes("e.alertState==='UNAWARE'||!locallyInformed")||!enemy.includes('alertedEscortIds'))fail.push('local escort knowledge boundary missing');
if(all.some(p=>rel(p)==='js/data/multi-theater-campaigns.js')){if(selector.includes('id="campaignDefinitionSelect"')||selector.includes('id="warPartySelect"'))fail.push('native campaign/war-party selects remain');if(!selector.includes('campaignAccess('))fail.push('campaign progression gate missing');}
console.log(JSON.stringify({ok:!fail.length,root,files:all.length,bytes:values,budgets,fail},null,2));if(fail.length)process.exit(1);
